### ISSUE TITLE
Why was the code cleared

### ISSUE THREAD

**Issue by he455** [BICLab/T-RevSNN#1]

**Comment by Blyzes** [comment]
@he455 I tried to email the author for the code and was told they would release it in July. But it hasn’t been released yet.

**Comment by hhx0320** [comment]
> @he455 I tried to email the author for the code and was told they would release it in July. But it hasn’t been released yet. If you want to discuss it, please contact me via qq1750636961 or email me at [1750636961@qq.com](mailto:1750636961@qq.com).



> @he455 I tried to email the author for the code and was told they would release it in July. But it hasn’t been released yet. If you want to discuss it, please contact me via qq1750636961 or email me at [1750636961@qq.com](mailto:1750636961@qq.com).

关闭时间上的梯度传播在代码中具体是怎么关闭的。


How is the gradient propagation on time turned off in the code.

**Comment by hhx0320** [comment]
> @he455 I tried to email the author for the code and was told they would release it in July. But it hasn’t been released yet. If you want to discuss it, please contact me via qq1750636961 or email me at [1750636961@qq.com](mailto:1750636961@qq.com).

关闭时间上的梯度传播在代码中具体是怎么关闭的。

How is the gradient propagation on time turned off in the code.

**Comment by Blyzes** [comment]
> 
> 关闭时间上的梯度传播在代码中具体是怎么关闭的。
> 
> How is the gradient propagation on time turned off in the code.

You can refer to [SLTT](https://github.com/qymeng94/SLTT). It detaches the outputs of each layer at different timesteps during the forward propagation process.

**Comment by jkhu29** [comment]
Due to the open-source policy restrictions of the IA (Institute of Automation), we plan to release our code simultaneously as the I-LIF (ECCV2024) and the detection code of Spike-Driven Transformer V2. I am very sorry about this.

BTW, T-RevSNN totally differs from SLTT and OTTT.

**Comment by jkhu29** [comment]
Released.
